version: '3.3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: laikinas
        volumes:
            - postgresql-volume:/var/lib/postgresql/data
        restart: always
        ports: 
            - "5432:5432"
        extra_hosts:
        - "localhost:192.168.65.2"

    webapp:
        depends_on: 
            - db
        image: edsdck/octoroperty:latest
        ports: 
            - "8080:80"
            - "8081:443"

volumes:
    postgresql-volume:
        external: true