version: '3.3'

services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: laikinas
        volumes: 
           # - ./postgres-data:/var/lib/postgresql/data linux
            - postgresql-volume:/var/lib/postgresql/data
        restart: always
        ports: 
            - "5432:5432"

    webapp:
        depends_on: 
            - db
        build: 
            context: .
        image: edsdck/octoroperty:latest
        ports: 
            - "8080:80"

volumes:
    postgresql-volume:
        external: true